drop table [diamond]
drop table [accessory_image]
drop table [variant]

drop table [accessory]
drop table [setting_style]
drop table [accessory_type]
drop table [shape]
drop table [material]
drop table [__EFMigrationsHistory]