use [DATJ]
drop table [__EFMigrationsHistory]
drop table [accessory_image]
drop table [blog]
drop table [feedback]
drop table [payment_signature]
drop table [payment_transaction]
drop table [transaction]
drop table [warranty_request]
drop table [warranty_card]
drop table [order_detail]
drop table [order]
drop table [material_price]
drop table [diamond_price]
drop table [accessory]
drop table [accessory_type]
drop table [diamond]
drop table [shape]
drop table [promotion]
drop table [price_rate]
drop table [account]
drop table [rank]
drop table [payment_notification]
drop table [payment]
drop table [payment_destination]
drop table [merchant]



