drop table [diamond]
drop table [variant_image]
drop table [variant]

drop table [setting]
drop table [setting_style]
drop table [setting_type]
drop table [shape]
drop table [material]
drop table [__EFMigrationsHistory]